🗃️  modified: init/nodejs/init 🗃️

diff --git a/init/nodejs/init b/init/nodejs/init
--- a/init/nodejs/init
+++ b/init/nodejs/init
@@ -1,37 +1,44 @@
 #!/usr/bin/env bash
-
-SCRIPTNAME="$(basename $0)"
-SCRIPTDIR="$(dirname "${BASH_SOURCE[0]}")"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+##@Version           :  GEN_SCRIPT_REPLACE_VERSION
+# @Author            :  GEN_SCRIPT_REPLACE_AUTHOR
+# @Contact           :  GEN_SCRIPT_REPLACE_EMAIL
+# @License           :  GEN_SCRIPT_REPLACE_LICENSE
+# @ReadME            :  GEN_SCRIPT_REPLACE_FILENAME --help
+# @Copyright         :  GEN_SCRIPT_REPLACE_COPYRIGHT
+# @Created           :  GEN_SCRIPT_REPLACE_DATE
+# @File              :  GEN_SCRIPT_REPLACE_FILENAME
+# @Description       :  GEN_SCRIPT_REPLACE_DESC
+# @TODO              :  GEN_SCRIPT_REPLACE_TODO
+# @Other             :  GEN_SCRIPT_REPLACE_OTHER
+# @Resource          :  GEN_SCRIPT_REPLACE_RES
+# @sudo/root         :  no
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+PROG="$(basename "$0" 2>/dev/null)"
 USER="${SUDO_USER:-${USER}}"
-
+HOME="${USER_HOME:-${HOME}}"
+SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# @Author      : Jason
-# @Contact     : casjaysdev@casjay.net
-# @File        : init
-# @Created     : Mon, Dec 31, 2019, 00:00 EST
-# @License     : WTFPL
-# @Copyright   : Copyright (c) CasjaysDev
-# @Description : init script for docker containers
-#
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+if ! cd "$SRC_DIR"; then
+  echo "Failed to cd into $SCRIPTDIR"
+  exit 1
+fi
+echo "entering $PWD and running mongod ; server/start.sh ; client/start.sh " >../app.log 2>&1
+echo >>./app.log
 
-cd "$SCRIPTDIR"
-echo "entering $PWD and running mongod ; server/start.sh ; client/start.sh " > ../app.log 2>&1
-echo >> ./app.log
-
-if [ ! -z "$MONGDB" ]; then
-  mongod -vvvv > ./mongo.app.log 2>&1 &
+if [ -n "$MONGDB" ]; then
+  mongod -vvvv >./mongo.app.log 2>&1 &
 fi
 
 if [ -d "$SCRIPTDIR/server" ]; then
-  server/start.sh &
+  server/start.sh >>../app.log 2>&1 &
 fi
 
 if [ -d "$SCRIPTDIR/client" ]; then
-  client/start.sh &
+  client/start.sh >>../app.log 2>&1 &
 fi
 
-echo "exit = $?" >> ../app.log 2>&1
+echo "exit = $?" >>../app.log 2>&1
 
 tail -f ./app.log ./mongo.app.log
 
